<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\AtomicNotes.Core\AtomicNotes.Core.csproj" />
    <ProjectReference Include="..\AtomicNotes.Data\AtomicNotes.Data.csproj" />
    <ProjectReference Include="..\AtomicNotes.Services\AtomicNotes.Services.csproj" />
    <ProjectReference Include="..\AtomicNotes.App\AtomicNotes.App.csproj" />
  </ItemGroup>
</Project>
